image: registry.gitlab.com/gianet/moegui/devops/linux-containers/ansible:2.9

before_script:
  - pip3 install ansible-lint
  - ansible-lint --version

stages:
  - ansible-lint

ansible-lint:
  stage: ansible-lint
  script:
    - ansible-lint .