image: registry.gitlab.com/gianet/moegui/devops/devops/ansible:2.9

# before_script:
#   - pip3 install ansible-base ansible-lint==4.*
#   - ansible-lint --version

stages:
  - ansible-lint

ansible-lint:
  stage: ansible-lint
  script:
    - ansible-lint .
