---
- name: Create PostgreSQL directory
  file:
    path: /home/{{default_user}}/postgres/
    state: directory  

- name: PostgreSQL Data Volume
  docker_volume:
    name: postgres_data
    state: present

- name: PostgreSQL config file
  template:
    src: postgresql.conf.j2
    dest: /home/{{default_user}}/postgres/postgresql.conf    

- name: PostgreSQL
  docker_container:
    name: "postgres"
    image: "postgres:{{ BUILD }}"
    command: "-c 'config_file=/etc/postgresql/postgresql.conf'"
    pull: "true"
    recreate: "yes"
    env:
      POSTGRES_USER: "{{ ROOT_USERNAME }}"
      POSTGRES_PASSWORD: "{{ ROOT_PASSWORD }}"
    state: "started"
    restart_policy: "unless-stopped"
    published_ports:
      - "0.0.0.0:{{ PORT }}:{{ PORT }}"
    volumes:
      - /home/{{default_user}}/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - postgres_data:/var/lib/postgresql/data