---
- name: Create PostgreSQL directory
  file:
    path: /home/{{ default_user }}/{{ DOCKER_NAME }}/
    state: directory
    mode: 0644

- name: PostgreSQL Data Volume
  docker_volume:
    name: "{{ DOCKER_NAME }}_data"
    state: "{{ VOLUME_STATE }}"

- name: PostgreSQL config file
  template:
    src: postgresql.conf.j2
    dest: /home/{{ default_user }}/{{ DOCKER_NAME }}/postgresql.conf
    mode: 0644

- name: PostgreSQL
  docker_container:
    name: "{{ DOCKER_NAME }}"
    image: "postgres:{{ BUILD }}"
    command: "-c 'config_file=/etc/postgresql/postgresql.conf'"
    pull: "true"
    recreate: "yes"
    env:
      POSTGRES_USER: "{{ ROOT_USERNAME }}"
      POSTGRES_PASSWORD: "{{ ROOT_PASSWORD }}"
    cpu_period: "{{ DOCKER_CPU_PERIOD }}"
    cpu_quota: "{{ DOCKER_CPU_QUOTA }}"
    memory: "{{ DOCKER_MEMORY }}"
    state: "{{ CONTAINER_STATE }}"
    restart_policy: "unless-stopped"
    published_ports:
      - "0.0.0.0:{{ PORT }}:{{ PORT }}"
    volumes:
      - /home/{{ default_user }}/{{ DOCKER_NAME }}/postgresql.conf:/etc/postgresql/postgresql.conf
      - '{{ DOCKER_NAME }}_data:/var/lib/postgresql/data'